server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.148.103:8848
        service: gulimall-gateway

    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq
